Added pin icon behind user marker images.
Vazerthon/funfunforum-usermap pull request #21
Opened 2017-08-29 23:18 UTC by justinryder

Based on the suggestion in [this post](https://www.funfunforum.com/t/show-us-where-you-are-fff-user-map/1659/75), I added back the marker icon behind the user marker profile images.

2017-08-30 13:59 UTC, Vazerthon requested changes
Looks really cool. If you could take the width and height out of the `img` tag please that'd be ace :-)

2017-08-30 13:59 UTC, Vazerthon commented on src/services/user-map-service.js
> +    html: `<img class="marker-user-icon__image" width="28" height="28" src="https://cdn-standard6.discourse.org/user_avatar/www.funfunforum.com/${username}/90/149_1.png" />`,
Could you remove `width="28" height="28"` from here as it's being set in CSS

2017-08-30 15:34 UTC, Vazerthon commented on src/services/user-map-service.js
>      shadowUrl: null,
Just realised, we can also re-enable the default shadow now

2017-08-30 21:44 UTC, justinryder commented
Good catch, I forgot to remove those attributes once I got the wrapping div sized properly. Updated!

I looked into re-enabling the shadows since you mentioned it, but [the divIcon doc](http://leafletjs.com/reference-1.2.0.html#divicon) says shadow options are ignored. :(

2017-08-31 07:42 UTC, Vazerthon approved these changes
🎉 Awesome work!

2017-08-31 07:43 UTC, merged